class BootstrapServices < ActiveRecord::Migration
  def self.up
    Service.create :name => "Web Application Development", :short_name => "Web application development", :image_url => "svc_rails_50.png", :description => "Custom, scalable web applications developed in Ruby on Rails, Java and php."
    Service.create :name => "iPhone App Development", :short_name => "iPhone apps", :image_url => "svc_iphone_50.png", :description => "Dynamic apps and websites optimized for the most exciting platform on the planet."
    Service.create :name => "Rapid Prototyping", :short_name => "Rapid prototyping", :image_url => "svc_rapid_50.png", :description => "Fully functional proof of concept frameworks developed very rapidly using Ruby on Rails."
    Service.create :name => "Software Development", :short_name => "Software development", :image_url => "svc_software_50.png", :description => "Desktop applications capable of running on any operating system."
    Service.create :name => "Database Design and Administration", :short_name => "Database administration", :image_url => "svc_database_50.png", :description => "Schema and database creation, database tuning, stored procedure development, and database administration."
    Service.create :name => "Legacy Systems Integration", :short_name => "Legacy systems integration", :image_url => "svc_legacy_50.png", :description => "Integration of modern applications and systems with legacy infrastructures and application frameworks."
    Service.create :name => "Server Administration", :short_name => "Server administration", :image_url => "svc_server_admin_50.png", :description => "Unix, linux and Apple server set-up, installation and administration."
    Service.create :name => "Systems Architecture", :short_name => "Systems architecture", :image_url => "svc_sys_design_50.png", :description => "Servers, storage arrays, firewalls, cloud computing instances, and network integration design."
    Service.create :name => "Application Scaling", :short_name => "Application scaling", :image_url => "svc_scale_50.png", :description => "Multi-tiered systems design with edge caching, load balancing, master-slave database architecture, replication, mirroring, and fail-over."
    Service.create :name => "User Interface Design", :short_name => "User interface design", :image_url => "svc_ui_50.png", :description => "User-centric interfaces designed with accessibility, ease-of-use, and pleasant aesthetics in mind."
    Service.create :name => "Ruby on Rails Application Development", :short_name => "Ruby on Rails", :image_url => "svc_rails_50.png", :description => "Rapidly developed web applications for external or internal use. We have experience in scaling large Rails installations."
    Service.create :name => "Java Application Extension and Integration", :short_name => "Java", :image_url => "svc_java_50.png", :description => "Extension of or integration with existing Java application frameworks. Specializing in JRuby."
    Service.create :name => "php Application Customization", :short_name => "php", :image_url => "svc_php_50.png", :description => "Modifying, extending and customizing existing php applications, particularly Open Source CMS systems such as Joomla! and Wordpress."
    Service.create :name => "Shell Scripting", :short_name => "Shell scripting", :image_url => "svc_shell_50.png", :description => "Server and application automation through robust, custom shell scripts."
    Service.create :name => "Usability Testing", :short_name => "Usability testing", :image_url => "svc_usability_50.png", :description => "Target audience users selected and monitored as they interact with your site or application and a full report along with recommendations given."
    Service.create :name => "Cloud Computing", :short_name => "Cloud computing", :image_url => "svc_cloud_50.png", :description => "Robust, infinitely scalable, n-tiered server instances designed to be deployed in minutes hosted in the Amazon Elastic Computing Cloud."
    Service.create :name => "Code Review", :short_name => "Code review", :image_url => "svc_code_review_50.png", :description => "Code analyzed for testing coverage, redundancy, maintainability, and execution efficiency."
    Service.create :name => "Automated Testing", :short_name => "Automated testing", :image_url => "svc_auto_test_50.png", :description => "Automated test development and implementation. Continuous Integration server set-up. Unit, functional and story-driven integration tests."
    Service.create :name => "Project Rescue", :short_name => "Project rescue", :image_url => "svc_rescue_50.png", :description => "Situational analysis, project success planning, staff replacement/supplementation, and complete framework re-implementations."
    Service.create :name => "Project Consulting", :short_name => "Project consulting", :image_url => "svc_consult_50.png", :description => "Complete life-cycle project consulting including analysis, requirements gathering, documentation, implementation, and launch."
    Service.create :name => "Strategic Planning", :short_name => "Strategic planning", :image_url => "svc_strategy_50.png", :description => "Long-term planning, trend analysis, and organizational directional planning as it pertains to technology implementations and online strategy."
    Service.create :name => "Technical Requirements", :short_name => "Technical requirements", :image_url => "svc_document_50.png", :description => "Complete and thorough technical documentation designed by developers for developers with ease-of-implementation as a primary goal."
    Service.create :name => "Functional Requirements", :short_name => "Functional requirements", :image_url => "svc_document_50.png", :description => "Clear and simple functional requirements documents that facilitate proper technical requirements design."
    Service.create :name => "Application Testing", :short_name => "Application testing", :image_url => "svc_usability_50.png", :description => "Putting an application through its paces by senior developers who are experienced in uncovering bugs."
    Service.create :name => "Load Testing", :short_name => "Load testing", :image_url => "svc_load_test_50.png", :description => "Automated load testing designed to simulate extreme traffic conditions along with comprehensive maximum load analyses."
    Service.create :name => "Search Engine Marketing", :short_name => "Search engine marketing", :image_url => "svc_sem_50.png", :description => "Keyphrase selection, code optimization, copy writing, blog commenting, link tracking, search engine submission, and ad-word analysis and recommendations."
    Service.create :name => "Social Media Marketing", :short_name => "Social media marketing", :image_url => "svc_social_50.png", :description => "Facebook applications, fan pages, and advertising combined with Twitter, LinkedIn and many other social networks specific to your targeted customer base."
    Service.create :name => "Website Design", :short_name => "Website design", :image_url => "svc_web_design_50.png", :description => "Site planning, copy writing, graphic creation, stock art purchasing, Photoshop comps, brand integration, HTML, CSS and Javascript coding."
    Service.create :name => "Landing Page Optimization", :short_name => "Landing page optimization", :image_url => "svc_landing_50.png", :description => "Specifically targeted landing pages integrated into your existing or new site that are designed explicitly to elicit a response from the visitor."
    Service.create :name => "Team Augmentation", :short_name => "Team augmentation", :image_url => "svc_staff_50.png", :description => "Staff supplementation with full-time or part-time employees and contractors, both locally and around the globe."
    Service.create :name => "Technical Resource Screening", :short_name => "Technical resource screening", :image_url => "svc_screen_50.png", :description => "Candidate qualifying with knowledgible subject matter experts specifically geared towards sorting the contenders from the pretenders."
    Service.create :name => "Security Analysis", :short_name => "Security analysis", :image_url => "svc_hacker_50.png", :description => "Gray-hat ethical hacking by not-so-nefarious experts determining your company's vulnerability to SQL-injection, Cross-site scripting (XSS), and other newsworthy security holes."
  end

  def self.down
    Service.delete_all
  end
end
